name: deepChroma_sdtw

channels:
  - defaults
  - conda-forge

dependencies:
  - python >=3.7.0, <4.0.0
  - pip >=19.2.0, <20.0.0
  - numpy >=1.17.0, <2.0.0
  - scipy >=1.3.0, <2.0.0
  - matplotlib >=3.1.0, <4.0.0
  - ipython >=7.8.0, <8.0.0
  - jupyter >=1.0.0, <2.0.0
  - pandas >=1.0.0, <2.0.0
  - numba >=0.51.0, <1.0.0
  - tqdm >=4.36.0, <5.0.0
  - h5py >= 3.0.0, <4.0.0 
  - pip:
    - mir-eval >=0.5.0, <1.0.0
    - librosa >=0.8.0, <1.0.0
    - pysoundfile >=0.9.0, <1.0.0
    - torch >= 1.0.0, <2.0.0 
    - torchinfo >= 1.7.0, < 2.0.0
    - libfmp
